version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Updated ZooKeeper image
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
      ZOOKEEPER_LISTENER_NAME: "listener"
      ZOOKEEPER_LISTENER_SECURITY_PROTOCOL: "PLAINTEXT"
      ZOOKEEPER_ADVERTISED_LISTENER_PORT: 2181
      ZOOKEEPER_ADVERTISED_LISTENER_NAME: "listener"
      ZOOKEEPER_LISTENERS: "PLAINTEXT://0.0.0.0:2181"
      ZOOKEEPER_ADVERTISED_LISTENERS: "PLAINTEXT://zookeeper:2181"
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka_network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # Expose Kafka on localhost:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_INTERNAL_HOSTNAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_PORT: 9092
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  create-topic:
    image: apache/kafka:latest
    container_name: create-topic
    command: ["bash", "-c", "/create-topics.sh"]
    environment:
      - TOPIC_NAME=kafka_training_Es  # Set topic name here
    volumes:
      - ./create-topics.sh:/create-topics.sh
    depends_on:
      - kafka
    networks:
      - kafka_network
    restart: "no"  # This service doesn't need to restart after running

networks:
  kafka_network:
    driver: bridge
