spring:


  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic



#    url: jdbc:mysql://localhost:3306/train_db  # Replace with your DB name
#    username: root  # Your MySQL username (NOT root for production!)
#    password: P@ssw0rd # Your MySQL password
#    driver-class-name: com.mysql.cj.jdbc.Driver # Essential for MySQL

#  jpa:
#    hibernate:
#      ddl-auto: update # Or create, none, validate, etc.  'update' is good for development
#    show-sql: true  # Optional: Show SQL in console (for debugging)
#    properties:
#      hibernate.format_sql: true # Optional: Format SQL in logs
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
  # Optional - If you want to configure a naming strategy for your tables/columns
  # jpa:
  #   hibernate:
  #     naming:
  #       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Or a custom strategy

server:
  port: 8080 # Or your preferred port

# Logging configuration (optional)
logging:
  level:
    root: INFO  # Or DEBUG for more detailed output
    org.hibernate.SQL: DEBUG # To see SQL statements
    org.hibernate.type.descriptor.sql: TRACE # To see data binding