spring.config.activate.on-profile: mysql  # Correct property for profile activation
#spring:
#  profiles: mysql  # This is incorrect
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_db  # MySQL DB URL
    username: root  # MySQL username
    password: P@ssw0rd  # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update  # You can change this (none, create, validate, etc.)
#    show-sql: true
    properties:
      hibernate.format_sql: true
