spring:

  profiles:
    active: postgres

  kafka:
    bootstrap-servers: 192.168.110.243:19091 # Kafka broker address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.trainproject.base.Util.Wapper.KafkaTransferWrapperSerializer  # <-- Custom serializer
      properties:
        spring:
          kafka:
            json:
              add:
                type:
                  headers: true # Ensures type headers are added to the Kafka message

    consumer:
      bootstrap-servers: 192.168.110.243:19091 # Replace with your Kafka brokers
      group-id: ${my.kafka.consumer-group-id}         # Replace with your desired group ID
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Deserializer for the key of the Kafka message (String in this case)
      value-deserializer: com.example.trainproject.base.Util.Wapper.TransferWrapperKafkaDeserializer # <-- Custom deserializer for the value
      auto-offset-reset: latest             # Or earliest
      enable-auto-commit: true             # Default is true
      auto-commit-interval: 5000           # in milliseconds (default: 5000)
      max-poll-records: 500                # Maximum number of records to fetch in a single poll
      fetch-min-bytes: 1024                # Minimum amount of data the server should return for a fetch request
      fetch-max-wait: 1000                # Maximum amount of time the server will block before answering the fetch request if there isn't sufficient data
      properties:
        spring:
          json:
            value:
              default:
                type: com.example.trainproject.base.Model.KafkaProduceMessage # Explicitly set the default type for deserialization if no type header is found
          trusted:
            packages: com.example.trainproject.base.Model, com.example.trainproject.base.Util.Wapper # Add the packages for trusted classes, including your custom ones
  liquibase:
    enabled: true
    change-log: /db/changelog/db.yml

  data:
    elasticsearch:
      client:
        reactive:
          endpoint: localhost:9200
      repositories:
        enabled: true

#  cloud:
#    vault:
#      uri: http://127.0.0.1:8200
#      token: hvs.TH8eeOix4dlffTyctwiypM8K
#      kv:
#        enabled: true
#        backend: secret
#        default-context: foo  # Correct path to the secret

#spring.config.import: vault:// # it is essential to have this , if not the application will not find the context in the secret
server:

  port: 8080
logging:

  level:
    liquibase: DEBUG
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springdoc: DEBUG
    org.springframework.cache : DEBUG
springdoc:

  swagger-ui:
    enabled: true
    layout: StandaloneLayout
    title: My Custom Swagger UI
    deep-linking: true
    url: /v3/api-docs
    css-url: /swagger-ui.css
Train:

  enableJob: false
my:

  kafka:
    topic: "kafka_training_Es"
    consumer-group-id: "my-consumer-group-id"
